[package]
name = "cfrename"
version = "0.4.0"
edition = "2024"
authors = ["swiizyy"]
description = "CLI tool for standardizing file renaming and organization"
license = "MIT"
repository = "https://github.com/swiizyy/cfrename"
readme = "README.md"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dialoguer = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
toml = "1.0.6"
chrono = "0.4"
anyhow = "1.0"
directories = "6.0.0"
shellexpand = "3.1"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.8"
proptest = "1.4"
