[package]
name = "cfrename"
version = "0.1.0"
edition = "2024"
authors = ["swiizyy"]
description = "CLI tool for standardizing file renaming and organization"
license-file = "LICENSE"
repository = "https://github.com/swiizyy/cfrename"
readme = "README.md"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dialoguer = "0.11"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
chrono = "0.4"
anyhow = "1.0"
directories = "5.0"
shellexpand = "3.1"
